shell:
    build: .
    command: /bin/bash
    environment:
        - DBNAME=mydb
        - DBHOST=pgdb
        - DBUSER=postgres
    links:
        - pgdb
    volumes:
        - .:/src

pgdb:
    image: postgres:latest
